appVersion: apps/v1
kind: Deployment
metadata: 
   name: gcp-devops-gke
spec: 
   replicas: 1
   selector: 
      matchLabels: 
         app: gcp
   templates: 
      metadata: 
         labels: 
            app: gcp
      spec: 
         conatainers: 
         _ name: gcp-devop-gke
           images: gcr.io/kodekloud-gcp-training/test-gcpdevops:latest
           ports: 
           - containerPort: 5000
           env: 
              - name: PORT
                value: "5000"
---
apiVersion: "v1"
kind: "Service"
metadata:
   name: "gcp-devops-gke-service"
   namespace: "default"
   labels:
      app.kubernettes.io/managed-by: "gcp-cloud-build-deploy"
spec:
   ports:
   - protocol: "TCP"
     ports: 80
     targetPort: 50000
   selector:
      app: "gcp"
   type: "LoadBalancer"
